name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout agbcc
        uses: actions/checkout@v4
        with:
          path: agbcc
          repository: kleeenexfeu/agbcc
          # originally going to pret/agbcc but I cloned it

      #- name: Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: '3.10'
      # for now this solution doesn't work

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev libelf-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Agbcc
        env:
          MODERN: 0
          COMPARE: 0
        run: make -j${nproc} -O all

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all

      - uses: actions/upload-artifact@v4
        with:
          name: emeraldbattlerevo
          path: emeraldbattlerevo.gba
          
      - uses: actions/upload-artifact@v4
        with:
          name: emeraldbattlerevo_elf
          path: emeraldbattlerevo.elf
          
      - uses: actions/upload-artifact@v4
        with:
          name: emeraldbattlerevo_map
          path: emeraldbattlerevo.map
